name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  CONTAINER_IMAGE: docker-overlord:${{ github.sha }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $CONTAINER_IMAGE
    
    - name: Set up Docker Hub
      run: echo $DOCKER_TOKEN | docker login --username=$DOCKER_USERNAME --password-stdin
    
    - name: Push to Docker Hub
      run: docker push $DOCKER_USERNAME/$CONTAINER_IMAGE
